### PR TITLE
Fix Calendar Todo view

### PR DESCRIPTION
**Pull request by Js41637**
Changed how it loads the events, the way it worked before was not ideal as it made styling very hard as most episodes were in different containers. Now it fetches an array of all episodes before the current day that isnt watched (within the month) and will show them.
#463

### CODE REVIEW

**Comment by garfield69** [comment]
Looks good. The one tiny niggle is that there are episodes presented that are outside of the month on display; is it worth filtering your fetched array to exclude episodes that are outside the displayed month?

**Comment by Js41637** [comment]
Well yeah but it uses the calendar as a base which also shows a few days of
the previous and next  month, you think I should limit it only to the
actual month?

**Comment by Js41637** [comment]
Ok so now it shows episodes that are in the current month and have aired/airing on the current day and if the episode isn't watched.

**Comment by garfield69** [comment]
>you think I should limit it only to the actual month?     

Yes, I though it would make sense that if the user selected December, then only episodes unwatched in December would be shown, since there are no longer any dates on the todo view, except the month banner at the top.    
Right now however, while this works neatly for January (the current month), view of any other prior month are empty, except December which is showing a few of January's episodes, so there is a fault in the logic someplace :-(

**Comment by garfield69** [comment]
Nice. tests all look good to me. are you done?

**Pull request merged**
