### PR TITLE
Update and rename en_us.json to el_GR.json

### PR DESCRIPTION
**Pull request by dzogas**
Incomplete Greek Translation of DuckieTV.
Is there a way to test it to make sure the translations are correct before commiting? 
This is the first time I am doing this in github....

### CODE REVIEW

**Review by Js41637 — CHANGES_REQUESTED** [review]
You just changed the en_us file to el_GR, you need to make a new file, not rename an existing.

**Comment by garfield69** [comment]
@dzogas wrote:      
>Is there a way to test it to make sure the translations are correct before commiting?       

First off, thank you for deciding to add Greek to DuckieTV.      

Yes, there is a way for you to test your changes before comitting, but before that happens I have to make some additions to DuckieTV source to add Greek as an available language option.      
So hold off on further translations while I make the necessary setup, and once I'm done I'll let you know how you can test your next batch of translations.       
IT would be helpful to know how you are currently doing the updates.... are you editing the file using the GitHub web editor, or from a plain text editor on your PC in conjunction with Desktop GitHub ?

**Comment by dzogas** [comment]
I don't even know how to reply to your message......
I used the Github web editor.

I will be waiting for your reply before translating more...

Also Js41637 requested a change which I really do not know how to do... Please, advise...

**Comment by garfield69** [comment]
Okely Dokely. DuckieTV is all set for Greek, so here are the steps:       
### refresh your fork (one time only)
You need to refresh your DuckieTV repository so you can work with an up to date source.      
- delete your existing fork by clicking on *settings* and scroll down to the *delete this repository*
image
image
- and now navigate to https://github.com/SchizoDuckie/DuckieTV and *fork* your repo
image
### edit your Greek translations and make your changes (repeat as often as necessary)
- in the _locales/ folder the file name is now el_gr.json      
- there is also another file that you could update to Greek, used when installing Chrome Extensions     
    it's in the _locales/el_GR/ folder and its called messages.json      
## These steps are for updating your PC so you can test your changes
### make an zip archive of your forked repo
- build a zip archive of your repo (repeat as often as required)
image
- extract the archive to your favourite working folder
### set up your Chrome Browser for testing (one time only)
- on your Chrome Browser, navigate to the chrome://extensions/ page
- check the *Developer mode* box
- click on the *load unpacked extensions* button
image
- find your extracted archive fiolder and click ok
image
- start your test DuckieTV and check your translations

- anytime you want to refresh your PC, close the DuckieTV extension, unpack and overwrite your extension folder from your latest zip archive, and start your test DuckieTV.

I'm closing this pull request as it is no longer necessary.

**Pull request closed without merging**
