### PR TITLE
Documentation for DuckieTV

### PR DESCRIPTION
**Pull request by RevTut**
Hi SchizoDuckie!

We have added two documents. If you could, we would like you to read the "Intro.md" in the ESOF-docs folder.

Regards,

### CODE REVIEW

**Comment by SchizoDuckie** [comment]
Hello,

Thanks for picking DuckieTV, that's pretty cool :)
I'm not certain what you want from me though, can you elaborate?

**Comment by RevTut** [comment]
Hi again!

We want to cooperate with you on this project (at least for the next semester) and provide you with documentation. However, in order to accomplish that, we need to understand how DuckieTV is structured. The answers we hope you can give to the questions in "intro.md" would provide the initial information we need in order to start working :)
For exemple do you develop one feature at a time? Have you created diagrams before coding? Have you based your project on an initial prototype? Do you follow a "test driven development"? etc.

Regards,

**Comment by SchizoDuckie** [comment]
Cool. I'll see if i can ansewr some for you tonight. Beware though, DuckieTV has no enforced strict standards or design /planinng phase anywhere, it's a project that I started to learn some angular, so many things just evolve kind of naturally. More on that tonight.

**Comment by Nutil** [comment]
Thank you for the quick answer :) We'll be waiting on tonight then.

Best regards.

**Comment by SchizoDuckie** [comment]
Allright, I promised you guys a more elaborate answer!

> What kind of Software Process Model have you followed to create DuckieTV?
> 1. Waterfall Model
> 2. Incremental Development and Delivery (release often, release early)

DuckieTV is very much like number 2: incremental development and delivery project. 
Things are prototyped, mostly not even sketched out but are just ideas or concepts that grow in our minds and then specced out as we go. We have as little as possible Project Managent like cruft in the team and often many things are being worked at at the same time.

Users submit ideas, and we as the DuckieTV team have ideas too. These are discussed either in tickets and specced as todo list items and with maybe some mockups in tickets. 

Examples here:

- https://github.com/SchizoDuckie/DuckieTV/issues/527
- https://github.com/SchizoDuckie/DuckieTV/issues/423
- https://github.com/SchizoDuckie/DuckieTV/issues/550

Since DuckieTV was started as a project for me to learn AngularJS, I've tried to share much of what i've learned either in code comments or in markdown files like [HACKING.md](https://github.com/SchizoDuckie/DuckieTV/blob/angular/HACKING.md) and [EVENTS.md](https://github.com/SchizoDuckie/DuckieTV/blob/angular/EVENTS.md) to the rest of the team and github.

There is also a long open active ticket https://github.com/SchizoDuckie/DuckieTV/issues/95 that track some of the documentation process and shows some dependency graphs.

I hope this gets you started! If you have any more questions just ask. Not sure i'm going to accept this initial pull request though, as it's basically an issue!

**Comment by Js41637** [comment]
Yeah not much of the design aspects are sketched out prior to just going straight in and seeing what you can do and what you think works. Having said that though, when coming up with the ideas of using sidepanels as the main navigation for series and episodes details, there was some initial layouts I made up of how it could look and work.
image
image
After that we just got the basic HTML layout & core JS to make it open and then played around in the Dev Tools to do the positioning and design and see what looks good and what can be done.

**Comment by Nutil** [comment]
Hey,

thank you for the information! I don't think we'd ever have been able to find all of that out by ourselves. We sent you the document as a pull-request because we couldn't find a better way to grab your attention, it's alright if you don't merge it onto the master.

For now, we'll work on making our initial review of the project's structure based on the information we now have, and we'll try and pinpoint where we think you could change your structure for the better (with little effort of course, keeping in mind it's a project for fun) and also where you did things better than we expected :)

We expect to have the review ready by monday for our teacher to evaluate, so we'll probably share it here within the next week!

Best regards!

**Comment by SchizoDuckie** [comment]
Excellent. Looking forward to it!

I do think 2 days is very little time to do a full review of 2 years of DuckieTV code, so you guys have a big task at hand! Some cool parts to look at may be CreateReadUpdateDelete.js (WebSQL abstraction / ORM) and the implementation of the generic torrentclients and generic torrentsearch. Love to hear you guys' feedback on that!

Also for your perspective, one more philosophy I apply to the project is not to prematurely optimize things. It's okay if the initial implementation of something is a somewhat hacky job, as long as things improve when they iterate and get refactored into something reusable when they touch multiple parts of the app. 

Closing this for now, feel free to open an issue with the results. Good luck!

**Pull request closed without merging**
