### PR TITLE
Update and rename en_us.json to sk_sk.json

### PR DESCRIPTION
**Pull request by dalukac**
Started with Slovak translation of DuckieTV

### CODE REVIEW

**Comment by garfield69** [comment]
Terrific. 
Do you want me to integrate the slovak support now, or wait until you have completed the conversion?

**Comment by dalukac** [comment]
I translated around 230 lines today. I don't know.. what is better for you

**Comment by garfield69** [comment]
I've added support for Slovak and integrated the work you have done so far.

I have found that contributers discover that translation is a large job that can take time, and often find it easier to see the results of their work in action for validation as they go along.
it is usual to discover that what looks correct having just translated the english into its equivalent, does not quite fit contexually when they see it on the buttons or panels etc, requireing further amendments.

in about 5 hours or so the first nightly with Slovak will be generated and you can check your progress so far and validate that I have got the language and country correctly spelled in Slovak (google translate is not that reliable) on the language settings panel ;-)

take a fresh fork of this repo before you continue making translations. 
Also please translate `_locales\sk_SK\messages.json` and clone it to `_locales\sk\messages.json`. (used for the chrome store extensions install).
and you may want to check that `_locales\angular-locale_sk_sk.js` and its clone `_locales\angular-locale_sk.js` (used for locale date/time presentation) are correct.

Cheers.

**Comment by garfield69** [comment]
if you are wondering how to refresh your fork and continue adding slovak translations just click [here](https://github.com/SchizoDuckie/DuckieTV/edit/angular/_locales/sk_sk.json)

**Pull request closed without merging**
