### PR TITLE
Cookie store

### PR DESCRIPTION
**Pull request by davehenton**

### CODE REVIEW

**Comment by SchizoDuckie** [comment]
What do we need a cookie store for?

**Comment by davehenton** [comment]
ah, my apologies! i was testing out an angular.js linter and pushed to the wrong fork.

**Comment by SchizoDuckie** [comment]
No problem, can happen. What does the linter do? You building something
new?

Op 19 jan. 2017 12:27 a.m. schreef "Dave Henton" <notifications@github.com>:

**Comment by Js41637** [comment]
lmao

**Pull request closed without merging**
